load('config.js');
function execute() {
    return Response.success([
        {title: "Adult", input: BASE_URL + "/tim-truyen/adult", script: "gen.js"},
        {title: "Ahegao", input: BASE_URL + "/tim-truyen/ahegao", script: "gen.js"},
        {title: "Bạo Dâm", input: BASE_URL + "/tim-truyen/bao-dam", script: "gen.js"},
        {title: "Big Boobs", input: BASE_URL + "/tim-truyen/big-boobs", script: "gen.js"},
        {title: "Blowjobs", input: BASE_URL + "/tim-truyen/blowjobs", script: "gen.js"},
        {title: "Cheating", input: BASE_URL + "/tim-truyen/cheating", script: "gen.js"},
        {title: "Chơi Hai Lỗ", input: BASE_URL + "/tim-truyen/choi-hai-lo", script: "gen.js"},
        {title: "Deo kinh", input: BASE_URL + "/tim-truyen/deo-kinh", script: "gen.js"},
        {title: "Đổ Boi", input: BASE_URL + "/tim-truyen/do-boi", script: "gen.js"},
        {title: "Doujinshi", input: BASE_URL + "/tim-truyen/doujinshi", script: "gen.js"},
        {title: "Drama", input: BASE_URL + "/tim-truyen/drama", script: "gen.js"},
        {title: "Ecchi", input: BASE_URL + "/tim-truyen/ecchi", script: "gen.js"},
        {title: "Gia đình", input: BASE_URL + "/tim-truyen/gia-dinh", script: "gen.js"},
        {title: "Yaoi", input: BASE_URL + "/tim-truyen/yaoi", script: "gen.js"},
        {title: "Giáo Viên", input: BASE_URL + "/tim-truyen/giao-vien", script: "gen.js"},
        {title: "Group", input: BASE_URL + "/tim-truyen/group", script: "gen.js"},
        {title: "Hầm Hiếp", input: BASE_URL + "/tim-truyen/ham-hiep", script: "gen.js"},
        {title: "Harem", input: BASE_URL + "/tim-truyen/harem", script: "gen.js"},
        {title: "Hậu Môn", input: BASE_URL + "/tim-truyen/hau-mon", script: "gen.js"},
        {title: "Hiếp Dâm", input: BASE_URL + "/tim-truyen/hiep-dam", script: "gen.js"},
        {title: "Housewife", input: BASE_URL + "/tim-truyen/housewife", script: "gen.js"},
        {title: "Không Che", input: BASE_URL + "/tim-truyen/khong-che", script: "gen.js"},
        {title: "Lão Già Dâm", input: BASE_URL + "/tim-truyen/lao-gia-dam", script: "gen.js"},
        {title: "Lồ nhị", input: BASE_URL + "/tim-truyen/lo-nhi", script: "gen.js"},
        {title: "Loạn Luân", input: BASE_URL + "/tim-truyen/loan-luan", script: "gen.js"},
        {title: "Loli", input: BASE_URL + "/tim-truyen/loli", script: "gen.js"},
        {title: "Milf", input: BASE_URL + "/tim-truyen/milf", script: "gen.js"},
        {title: "Mind Break", input: BASE_URL + "/tim-truyen/mind-break", script: "gen.js"},
        {title: "Mind Control", input: BASE_URL + "/tim-truyen/mind-control", script: "gen.js"},
        {title: "Mông to", input: BASE_URL + "/tim-truyen/mong-to", script: "gen.js"},
        {title: "Nakadashi", input: BASE_URL + "/tim-truyen/nakadashi", script: "gen.js"},
        {title: "Ngọt", input: BASE_URL + "/tim-truyen/ngot", script: "gen.js"},
        {title: "Ngực Lớn", input: BASE_URL + "/tim-truyen/nguc-lon", script: "gen.js"},
        {title: "Ngực Nhỏ", input: BASE_URL + "/tim-truyen/nguc-nho", script: "gen.js"},
        {title: "NTR", input: BASE_URL + "/tim-truyen/ntr", script: "gen.js"},
        {title: "Nữ Sinh", input: BASE_URL + "/tim-truyen/nu-sinh", script: "gen.js"},
        {title: "One Shot", input: BASE_URL + "/tim-truyen/one-shot", script: "gen.js"},
        {title: "Oneshot", input: BASE_URL + "/tim-truyen/oneshot", script: "gen.js"},
        {title: "Romance", input: BASE_URL + "/tim-truyen/romance", script: "gen.js"},
        {title: "SchoolGirl", input: BASE_URL + "/tim-truyen/schoolgirl", script: "gen.js"},
        {title: "Series", input: BASE_URL + "/tim-truyen/series", script: "gen.js"},
        {title: "Sex Toys", input: BASE_URL + "/tim-truyen/sex-toys", script: "gen.js"},
        {title: "Shota", input: BASE_URL + "/tim-truyen/shota", script: "gen.js"},
        {title: "Smut", input: BASE_URL + "/tim-truyen/smut", script: "gen.js"},
        {title: "Succubus", input: BASE_URL + "/tim-truyen/succubus", script: "gen.js"},
        {title: "Swimsuit", input: BASE_URL + "/tim-truyen/swimsuit", script: "gen.js"},
        {title: "Thủ dâm", input: BASE_URL + "/tim-truyen/thu-dam", script: "gen.js"},
        {title: "Truyện dài", input: BASE_URL + "/tim-truyen/truyen-dai", script: "gen.js"},
        {title: "Truyện Màu", input: BASE_URL + "/tim-truyen/truyen-mau", script: "gen.js"},
        {title: "Truyện Ngắn", input: BASE_URL + "/tim-truyen/truyen-ngan", script: "gen.js"},
        {title: "Vét máng", input: BASE_URL + "/tim-truyen/vet-mang", script: "gen.js"},
        {title: "Vếu to", input: BASE_URL + "/tim-truyen/veu-to", script: "gen.js"},
        {title: "Virgin", input: BASE_URL + "/tim-truyen/virgin", script: "gen.js"}
    ]);
}