function execute() {
    // Thay đổi url trang web tại đây
    const baseUrl = "https://truyendocviet1.xyz"; 

    return Response.success([
        { title: "Truyện dành riêng cho VIP", input: baseUrl + "/truyen-danh-rieng-cho-vip.html", script: "gen.js" },
        { title: "Truyện Kiếm hiệp", input: baseUrl + "/truyen-kiem-hiep.html", script: "gen.js" },
        { title: "Truyện Quân sự", input: baseUrl + "/truyen-quan-su.html", script: "gen.js" },
        { title: "Truyện Tiên Hiệp", input: baseUrl + "/truyen-tien-hiep.html", script: "gen.js" },
        { title: "Cổ Tiên Hiệp", input: baseUrl + "/co-tien-hiep.html", script: "gen.js" },
        { title: "Truyện Hệ thống", input: baseUrl + "/truyen-he-thong.html", script: "gen.js" },
        { title: "Truyện Dị giới", input: baseUrl + "/truyen-di-gioi.html", script: "gen.js" },
        { title: "Truyện Huyền ảo", input: baseUrl + "/truyen-huyen-ao.html", script: "gen.js" },
        { title: "Truyện Khoa Huyễn", input: baseUrl + "/truyen-khoa-huyen.html", script: "gen.js" },
        { title: "Truyện Xuyên Không", input: baseUrl + "/truyen-xuyen-khong.html", script: "gen.js" },
        { title: "Truyện Huyền Huyễn", input: baseUrl + "/truyen-huyen-huyen.html", script: "gen.js" },
        { title: "Truyện Lịch sử", input: baseUrl + "/truyen-lich-su.html", script: "gen.js" },
        { title: "Truyện Ngôn Tình", input: baseUrl + "/truyen-ngon-tinh.html", script: "gen.js" },
        { title: "Hậu Cung", input: baseUrl + "/hau-cung.html", script: "gen.js" },
        { title: "Truyện Đô Thị", input: baseUrl + "/truyen-do-thi.html", script: "gen.js" },
        { title: "Truyện Trinh Thám", input: baseUrl + "/truyen-trinh-tham.html", script: "gen.js" },
        { title: "Truyện Cổ Đại", input: baseUrl + "/truyen-co-dai.html", script: "gen.js" },
        { title: "Truyện Võng Du", input: baseUrl + "/truyen-vong-du.html", script: "gen.js" },
        { title: "Truyện Quan Trường", input: baseUrl + "/truyen-quan-truong.html", script: "gen.js" },
        { title: "Truyện Mạt Thế", input: baseUrl + "/truyen-mat-the.html", script: "gen.js" },
        { title: "Sách Khoa Học", input: baseUrl + "/sach-khoa-hoc.html", script: "gen.js" },
        { title: "Truyện Ma", input: baseUrl + "/truyen-ma.html", script: "gen.js" },
        { title: "Tâm Linh - Tôn Giáo", input: baseUrl + "/tam-linh-ton-giao.html", script: "gen.js" },
        { title: "Truyện Linh Dị", input: baseUrl + "/truyen-linh-di.html", script: "gen.js" },
        { title: "Truyện Dị Năng", input: baseUrl + "/truyen-di-nang.html", script: "gen.js" },
        { title: "Truyện Kinh Dị", input: baseUrl + "/truyen-kinh-di.html", script: "gen.js" },
        { title: "Truyện Hài Hước", input: baseUrl + "/truyen-hai-huoc.html", script: "gen.js" },
        { title: "Tu Chân", input: baseUrl + "/tu-chan.html", script: "gen.js" },
        { title: "Truyện Trùng Sinh", input: baseUrl + "/truyen-trung-sinh.html", script: "gen.js" },
        { title: "Toàn Dân", input: baseUrl + "/toan-dan.html", script: "gen.js" },
        { title: "Ngự Thú", input: baseUrl + "/ngu-thu.html", script: "gen.js" },
        { title: "Phim - Trò Chơi", input: baseUrl + "/tro-choi-dien-anh.html", script: "gen.js" },
        { title: "Cao Võ Thế Giới", input: baseUrl + "/cao-vo-the-gioi.html", script: "gen.js" },
        { title: "Ngu Nhạc Minh Tinh", input: baseUrl + "/ngu-nhac-minh-tinh.html", script: "gen.js" },
        { title: "Vô Sỉ", input: baseUrl + "/vo-si.html", script: "gen.js" },
        { title: "Chư Thiên Vạn Giới", input: baseUrl + "/chu-thien-van-gioi.html", script: "gen.js" },
        { title: "Mỹ Thực", input: baseUrl + "/my-thuc.html", script: "gen.js" },
        { title: "Bách Hợp", input: baseUrl + "/bach-hop.html", script: "gen.js" },
        { title: "Sủng", input: baseUrl + "/sung.html", script: "gen.js" },
        { title: "Nữ Cường", input: baseUrl + "/nu-cuong.html", script: "gen.js" },
        { title: "Trọng Sinh", input: baseUrl + "/trong-sinh.html", script: "gen.js" },
        { title: "Hiện Thực Bách Thái", input: baseUrl + "/hien-thuc-bach-thai.html", script: "gen.js" },
        { title: "Hiện Đại", input: baseUrl + "/hien-dai.html", script: "gen.js" },
        { title: "Tâm Lý", input: baseUrl + "/tam-ly.html", script: "gen.js" },
        { title: "Tác Đại Thần", input: baseUrl + "/tac-dai-than.html", script: "gen.js" },
        { title: "Ngọt Sủng", input: baseUrl + "/ngot-sung.html", script: "gen.js" },
        { title: "Điền Văn", input: baseUrl + "/dien-van.html", script: "gen.js" },
        { title: "Đồng Nhân", input: baseUrl + "/dong-nhan.html", script: "gen.js" },
        { title: "Làm Giàu", input: baseUrl + "/lam-giau.html", script: "gen.js" },
        { title: "Đoản Văn", input: baseUrl + "/doan-van.html", script: "gen.js" },
        { title: "Cung Đấu", input: baseUrl + "/cung-dau.html", script: "gen.js" },
        { title: "Gia Đấu", input: baseUrl + "/gia-dau.html", script: "gen.js" },
        { title: "Xây Dựng Thế Lực", input: baseUrl + "/xay-dung-the-luc.html", script: "gen.js" },
        { title: "Võ Hiệp", input: baseUrl + "/vo-hiep.html", script: "gen.js" },
        { title: "Sảng Văn", input: baseUrl + "/sang-van.html", script: "gen.js" },
        { title: "Tây Phương Kỳ Huyễn", input: baseUrl + "/tay-phuong-ky-huyen.html", script: "gen.js" },
        { title: "Phiêu Lưu", input: baseUrl + "/phieu-luu.html", script: "gen.js" },
        { title: "Cẩu Đạo", input: baseUrl + "/cau-dao.html", script: "gen.js" },
        { title: "Ngược", input: baseUrl + "/nguoc.html", script: "gen.js" },
        { title: "Sử Thi", input: baseUrl + "/su-thi.html", script: "gen.js" },
        { title: "Xuyên Sách", input: baseUrl + "/xuyen-sach.html", script: "gen.js" },
        { title: "Dưỡng Thê", input: baseUrl + "/duong-the.html", script: "gen.js" },
        { title: "Sáng Tác Việt", input: baseUrl + "/sang-tac-viet.html", script: "gen.js" },
        { title: "Phản Phái", input: baseUrl + "/phan-phai.html", script: "gen.js" },
        { title: "Vô Hạn Lưu", input: baseUrl + "/vo-han-luu.html", script: "gen.js" }
    ]);
}