load("config.js");

function execute() {
    return Response.success([
        { title: "Hentai Vietsub", input: BASE_URL + "/the-loai/vietsub", script: "gen.js" },
        { title: "Hentai 3D", input: BASE_URL + "/the-loai/3d", script: "gen.js" },
        { title: "Không Che", input: BASE_URL + "/the-loai/khong-che", script: "gen.js" },
        { title: "Mông To", input: BASE_URL + "/the-loai/big-boobs", script: "gen.js" },
        { title: "Học Sinh", input: BASE_URL + "/the-loai/school-girl", script: "gen.js" },
        { title: "Hiếp Dâm", input: BASE_URL + "/the-loai/rape", script: "gen.js" },
        { title: "Tự Sướng", input: BASE_URL + "/the-loai/thu-dam", script: "gen.js" },
        { title: "Tập Thể", input: BASE_URL + "/the-loai/threesome", script: "gen.js" },
        { title: "Cô Giáo", input: BASE_URL + "/the-loai/teacher", script: "gen.js" },
        { title: "Succubus", input: BASE_URL + "/the-loai/succubus", script: "gen.js" },
        { title: "Blow Job", input: BASE_URL + "/the-loai/blow-job", script: "gen.js" },
        { title: "Boob Job", input: BASE_URL + "/the-loai/boob-job", script: "gen.js" },
        { title: "Anal", input: BASE_URL + "/the-loai/anal", script: "gen.js" },
        { title: "Stocking", input: BASE_URL + "/the-loai/stocking", script: "gen.js" },
        { title: "Virgin", input: BASE_URL + "/the-loai/virgin", script: "gen.js" },
        { title: "Mind Break", input: BASE_URL + "/the-loai/mind-break", script: "gen.js" },
        { title: "Femdom", input: BASE_URL + "/the-loai/femdom", script: "gen.js" },
        { title: "Ahegao", input: BASE_URL + "/the-loai/ahegao", script: "gen.js" },
        { title: "Plot", input: BASE_URL + "/the-loai/plot", script: "gen.js" },
        { title: "Sex Toy", input: BASE_URL + "/the-loai/sex-toy", script: "gen.js" },
        { title: "Harem", input: BASE_URL + "/the-loai/harem", script: "gen.js" },
        { title: "Bondage", input: BASE_URL + "/the-loai/bondage", script: "gen.js" },
        { title: "Double Penetration", input: BASE_URL + "/the-loai/double-penetration", script: "gen.js" },
        { title: "Vanilla", input: BASE_URL + "/the-loai/vanilla", script: "gen.js" },
        { title: "Gang Bang", input: BASE_URL + "/the-loai/gang-bang", script: "gen.js" },
        { title: "Milf", input: BASE_URL + "/the-loai/milf", script: "gen.js" },
        { title: "Loạn Luân", input: BASE_URL + "/the-loai/loan-luan", script: "gen.js" },
        { title: "Mind Control", input: BASE_URL + "/the-loai/mind-control", script: "gen.js" },
        { title: "Tsundere", input: BASE_URL + "/the-loai/tsundere", script: "gen.js" },
        { title: "Yuri", input: BASE_URL + "/the-loai/yuri", script: "gen.js" },
        { title: "Loli", input: BASE_URL + "/the-loai/loli", script: "gen.js" },
        { title: "Romance", input: BASE_URL + "/the-loai/romance", script: "gen.js" },
        { title: "NTR", input: BASE_URL + "/the-loai/ntr", script: "gen.js" },
        { title: "Megane", input: BASE_URL + "/the-loai/megane", script: "gen.js" },
        { title: "Hầu gái - Maid", input: BASE_URL + "/the-loai/maid", script: "gen.js" },
        { title: "Orgy", input: BASE_URL + "/the-loai/orgy", script: "gen.js" },
        { title: "Bạo dâm - BDSM", input: BASE_URL + "/the-loai/bdsm", script: "gen.js" },
        { title: "Xúc tua - Tentacle", input: BASE_URL + "/the-loai/tentacle", script: "gen.js" },
        { title: "Monster", input: BASE_URL + "/the-loai/monster", script: "gen.js" },
        { title: "Đồ Bơi", input: BASE_URL + "/the-loai/do-boi", script: "gen.js" },
        { title: "Y Tá", input: BASE_URL + "/the-loai/y-ta", script: "gen.js" },
        { title: "Ugly Bastard", input: BASE_URL + "/the-loai/ugly-bastard", script: "gen.js" },
        { title: "Lactation", input: BASE_URL + "/the-loai/lactation", script: "gen.js" },
        { title: "Dark Skin", input: BASE_URL + "/the-loai/dark-skin", script: "gen.js" },
        { title: "Guro", input: BASE_URL + "/the-loai/guro", script: "gen.js" },
        { title: "Futanari", input: BASE_URL + "/the-loai/futanari", script: "gen.js" },
        { title: "Fantasy", input: BASE_URL + "/the-loai/fantasy", script: "gen.js" },
        { title: "Foot Job", input: BASE_URL + "/the-loai/foot-job", script: "gen.js" },
        { title: "Softcore", input: BASE_URL + "/the-loai/softcore", script: "gen.js" },
        { title: "X-Ray", input: BASE_URL + "/the-loai/x-ray", script: "gen.js" },
        { title: "Kemonomimi", input: BASE_URL + "/the-loai/kemonomimi", script: "gen.js" },
        { title: "Shota", input: BASE_URL + "/the-loai/shota", script: "gen.js" },
        { title: "Tống tình", input: BASE_URL + "/the-loai/tong-tinh", script: "gen.js" },
        { title: "Elf", input: BASE_URL + "/the-loai/elf", script: "gen.js" },
        { title: "Bao cao su", input: BASE_URL + "/the-loai/bao-cao-su", script: "gen.js" },
        { title: "Scat", input: BASE_URL + "/the-loai/scat", script: "gen.js" },
        { title: "Tiểu tiện", input: BASE_URL + "/the-loai/tieu-tien", script: "gen.js" },
        { title: "Quấy rối", input: BASE_URL + "/the-loai/quay-roi", script: "gen.js" },
        { title: "Josei", input: BASE_URL + "/the-loai/josei", script: "gen.js" },
        { title: "Thuốc", input: BASE_URL + "/the-loai/thuoc", script: "gen.js" },
        { title: "Cosplay", input: BASE_URL + "/the-loai/cosplay", script: "gen.js" },
        { title: "Thụ thai", input: BASE_URL + "/the-loai/thu-thai", script: "gen.js" },
        { title: "Trap", input: BASE_URL + "/the-loai/trap", script: "gen.js" },
        { title: "Yaoi", input: BASE_URL + "/the-loai/yaoi", script: "gen.js" },
        { title: "Gel bôi trơn", input: BASE_URL + "/the-loai/gel-boi-tron", script: "gen.js" },
        { title: "Ti thụt", input: BASE_URL + "/the-loai/ti-thut", script: "gen.js" },
        { title: "Pregnant", input: BASE_URL + "/the-loai/pregnant", script: "gen.js" },
        { title: "Impregnate", input: BASE_URL + "/the-loai/impregnate", script: "gen.js" },
    ]);
}