function execute() {
    return Response.success([
//        {title: "全部", input: null, script: "gen.js"},
        {title: "校园", input: "3", script: "gen.js"},
        {title: "爱情", input: "1", script: "gen.js"},
        {title: "冒险", input: "6", script: "gen.js"},
        {title: "搞笑", input: "10", script: "gen.js"},
        {title: "奇幻", input: "15", script: "gen.js"},
        {title: "魔法", input: "2", script: "gen.js"},
        {title: "异界", input: "17", script: "gen.js"},
        {title: "穿越", input: "18", script: "gen.js"},
        {title: "侦探", input: "8", script: "gen.js"},
        {title: "科幻", input: "4", script: "gen.js"},
        {title: "后宫", input: "12", script: "gen.js"},
        {title: "神鬼", input: "5", script: "gen.js"},
        {title: "其它", input: "9", script: "gen.js"},
        {title: "格斗", input: "11", script: "gen.js"},
        {title: "恐怖", input: "7", script: "gen.js"},
        {title: "百合", input: "20", script: "gen.js"},
        {title: "战争", input: "16", script: "gen.js"},
        {title: "异能", input: "14", script: "gen.js"},
        {title: "治愈", input: "21", script: "gen.js"},
        {title: "机战", input: "19", script: "gen.js"},
        {title: "励志", input: "23", script: "gen.js"},
        {title: "都市", input: "13", script: "gen.js"},
        {title: "历史", input: "22", script: "gen.js"},
        {title: "纯爱", input: "24", script: "gen.js"},
    ]);
}
