function execute() {
    return Response.success([
        { title: "BDSM", input: "https://doctruyen14.biz/tag/bdsm/", script: "gen.js" },
        { title: "bú lồn", input: "https://doctruyen14.biz/tag/bu-lon/", script: "gen.js" },
        { title: "bạo dâm", input: "https://doctruyen14.biz/tag/bao-dam/", script: "gen.js" },
        { title: "bố chồng", input: "https://doctruyen14.biz/tag/bo-chong/", script: "gen.js" },
        { title: "cha con", input: "https://doctruyen14.biz/tag/cha-con/", script: "gen.js" },
        { title: "chi gai", input: "https://doctruyen14.biz/tag/chi-gai/", script: "gen.js" },
        { title: "con dâu", input: "https://doctruyen14.biz/tag/con-dau-2/", script: "gen.js" },
        { title: "cuckold", input: "https://doctruyen14.biz/tag/cuckold/", script: "gen.js" },
        { title: "cô giáo", input: "https://doctruyen14.biz/tag/co-giao/", script: "gen.js" },
        { title: "doc truyen", input: "https://doctruyen14.biz/tag/doc-truyen/", script: "gen.js" },
        { title: "doc truyen cuoi", input: "https://doctruyen14.biz/tag/doc-truyen-cuoi/", script: "gen.js" },
        { title: "gai dam", input: "https://doctruyen14.biz/tag/gai-dam/", script: "gen.js" },
        { title: "gái dâm", input: "https://doctruyen14.biz/tag/gai-dam-3/", script: "gen.js" },
        { title: "gái xinh", input: "https://doctruyen14.biz/tag/gai-xinh/", script: "gen.js" },
        { title: "harem", input: "https://doctruyen14.biz/tag/harem/", script: "gen.js" },
        { title: "hiếp dâm", input: "https://doctruyen14.biz/tag/hiep-dam/", script: "gen.js" },
        { title: "hoc sinh", input: "https://doctruyen14.biz/tag/hoc-sinh/", script: "gen.js" },
        { title: "Khẩu Dâm", input: "https://doctruyen14.biz/tag/khau-dam/", script: "gen.js" },
        { title: "lam tinh", input: "https://doctruyen14.biz/tag/lam-tinh/", script: "gen.js" },
        { title: "Loan.luan", input: "https://doctruyen14.biz/tag/loan-luan/", script: "gen.js" },
        { title: "loạn luân", input: "https://doctruyen14.biz/tag/loan-luan-2/", script: "gen.js" },
        { title: "Lén Lút", input: "https://doctruyen14.biz/tag/len-lut/", script: "gen.js" },
        { title: "máy bay", input: "https://doctruyen14.biz/tag/may-bay/", script: "gen.js" },
        { title: "Mẹ Con", input: "https://doctruyen14.biz/tag/me-con/", script: "gen.js" },
        { title: "ngoại tình", input: "https://doctruyen14.biz/tag/ngoai-tinh/", script: "gen.js" },
        { title: "ntr", input: "https://doctruyen14.biz/tag/ntr/", script: "gen.js" },
        { title: "nô lệ", input: "https://doctruyen14.biz/tag/no-le/", script: "gen.js" },
        { title: "phi công", input: "https://doctruyen14.biz/tag/phi-cong/", script: "gen.js" },
        { title: "ren ri", input: "https://doctruyen14.biz/tag/ren-ri/", script: "gen.js" },
        { title: "slave", input: "https://doctruyen14.biz/tag/slave/", script: "gen.js" },
        { title: "some", input: "https://doctruyen14.biz/tag/some/", script: "gen.js" },
        { title: "sung suong", input: "https://doctruyen14.biz/tag/sung-suong/", script: "gen.js" },
        { title: "thu dam", input: "https://doctruyen14.biz/tag/thu-dam/", script: "gen.js" },
        { title: "truyen hay", input: "https://doctruyen14.biz/tag/truyen-hay/", script: "gen.js" },
        { title: "truyen loan luan", input: "https://doctruyen14.biz/tag/truyen-loan-luan/", script: "gen.js" },
        { title: "truyen nguoi lon", input: "https://doctruyen14.biz/tag/truyen-nguoi-lon/", script: "gen.js" },
        { title: "truyen sex", input: "https://doctruyen14.biz/tag/truyen-sex/", script: "gen.js" },
        { title: "truyen sex hay", input: "https://doctruyen14.biz/tag/truyen-sex-hay/", script: "gen.js" },
        { title: "truyen sex moi", input: "https://doctruyen14.biz/tag/truyen-sex-moi/", script: "gen.js" },
        { title: "truyen sex nguoi lon", input: "https://doctruyen14.biz/tag/truyen-sex-nguoi-lon-2/", script: "gen.js" },
        { title: "truyen teen", input: "https://doctruyen14.biz/tag/truyen-teen-2/", script: "gen.js" },
        { title: "tập thể", input: "https://doctruyen14.biz/tag/tap-the/", script: "gen.js" },
        { title: "vo dam", input: "https://doctruyen14.biz/tag/vo-dam/", script: "gen.js" },
        { title: "vung trom", input: "https://doctruyen14.biz/tag/vung-trom/", script: "gen.js" },
    ]);
}