function execute() {
    return Response.success([
        { title: "Chính trị", input: "/thoi-su/chinh-tri", script: "zen.js" },
        { title: "Dân sinh", input: "/thoi-su/dan-sinh", script: "zen.js" },
        { title: "Lao động - Việc làm", input: "/thoi-su/lao-dong-viec-lam", script: "zen.js" },
        { title: "Giao thông", input: "/thoi-su/giao-thong", script: "zen.js" },
        { title: "Tư liệu", input: "/the-gioi/tu-lieu", script: "zen.js" },
        { title: "Phân tích", input: "/the-gioi/phan-tich", script: "zen.js" },
        { title: "Người Việt 5 châu", input: "/the-gioi/nguoi-viet-5-chau", script: "zen.js" },
        { title: "Cuộc sống đó đây", input: "/the-gioi/cuoc-song-do-day", script: "zen.js" },
        { title: "Quân sự", input: "/the-gioi/quan-su", script: "zen.js" },
        { title: "Quốc tế", input: "/kinh-doanh/quoc-te", script: "zen.js" },
        { title: "Doanh nghiệp", input: "/kinh-doanh/doanh-nghiep", script: "zen.js" },
        { title: "Chứng khoán", input: "/kinh-doanh/chung-khoan", script: "zen.js" },
        { title: "Ebank", input: "/kinh-doanh/ebank", script: "zen.js" },
        { title: "Vĩ mô", input: "/kinh-doanh/vi-mo", script: "zen.js" },
        { title: "Tiền của tôi", input: "/kinh-doanh/tien-cua-toi", script: "zen.js" },
        { title: "Hàng hóa", input: "/kinh-doanh/hang-hoa", script: "zen.js" },
        { title: "Bảo hiểm", input: "/kinh-doanh/bao-hiem", script: "zen.js" },
        { title: "Chính sách", input: "/bat-dong-san/chinh-sach", script: "zen.js" },
        { title: "Thị trường", input: "/bat-dong-san/thi-truong", script: "zen.js" },
        { title: "Khoa học trong nước", input: "/khoa-hoc/khoa-hoc-trong-nuoc", script: "zen.js" },
        { title: "Tin tức", input: "/khoa-hoc/tin-tuc", script: "zen.js" },
        { title: "Phát minh", input: "/khoa-hoc/phat-minh", script: "zen.js" },
        { title: "Ứng dụng", input: "/khoa-hoc/ung-dung", script: "zen.js" },
        { title: "Thế giới tự nhiên", input: "/khoa-hoc/the-gioi-tu-nhien", script: "zen.js" },
        { title: "Thường thức", input: "/khoa-hoc/thuong-thuc", script: "zen.js" },
        { title: "Giới sao", input: "/giai-tri/gioi-sao", script: "zen.js" },
        { title: "Phim", input: "/giai-tri/phim", script: "zen.js" },
        { title: "Nhạc", input: "/giai-tri/nhac", script: "zen.js" },
        { title: "Hồ sơ", input: "/phap-luat/ho-so-pha-an", script: "zen.js" },
    ]);
}
